import './style.css';
import * as T from 'three';
import {createScene} from './scene';
import {Fluid} from './fluid';
import {defaults,MilkLedger,validPreset,type Preset} from './model';
document.querySelector('#app')!.innerHTML=`<main><header><span class="eyebrow">THE AFTERNOON POUR</span><h1>Little Latte<span>✦</span></h1><p>A little practice. A lovely pause.</p></header><section class="card"><div><span class="eyebrow">POURING STUDIO · SANDBOX</span><h2>Make something yours.</h2></div><span class="badge">No rush</span></section><div id="stage" aria-label="Latte art surface"></div><p id="hint">Hold & move over the cup to pour. Release to reposition.</p><section class="controls"><div class="row"><label>Pouring feel <select id="preset"><option>Drawing</option><option selected>Accessible</option><option>Technique</option></select></label><label id="heightLabel" hidden>Pour height <select id="height"><option value="low">Low · surface art</option><option value="high">High · mix in</option></select></label></div><div class="milk"><span>Milk in your pitcher</span><strong id="milk">100%</strong></div><progress id="budget" max="100" value="100"></progress><div class="row flow"><label>Flow <input id="flow" type="range" min="0.1" max="1" step="0.01" value="0.55"></label><button id="pour">Hold to pour</button></div><div class="row actions"><button id="reset">Fresh cup</button><button id="refill">Refill pitcher</button><button id="finish">Finish pour</button></div><p id="status" role="status">Your canvas is coffee. Enjoy the process.</p></section><details><summary>Studio settings</summary><div class="settings"><label><input id="left" type="checkbox"> Left-handed controls</label><label><input id="unlimited" type="checkbox"> Unlimited milk</label><label><input id="sound" type="checkbox"> Pour sound</label><label>Surface quality <select id="quality"><option>256</option><option>512</option></select></label><div id="tuning"></div><div class="row"><button id="save">Save preset</button><button id="restore">Reset preset</button><button id="export">Export tuning</button></div><label>Import tuning <input id="import" type="file" accept="application/json,.json"></label><small id="performance"></small></div></details><footer>A tiny coffee ritual · first pouring experiment</footer></main>`;
const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const range=el<HTMLInputElement>('flow');const preset=el<HTMLSelectElement>('preset');const ledger=new MilkLedger();
let presets:Record<string,Preset>=structuredClone(defaults);
try{const saved=JSON.parse(localStorage.getItem('little-latte-presets')||'null');if(saved&&Object.keys(defaults).every(k=>validPreset(saved[k])))presets=saved;}catch{/* Storage is optional. */}
const view=createScene(el('stage'));let fluid=new Fluid(view.renderer);let point=new T.Vector2(0,0),previous=point.clone();
let cupPointer:number|null=null,flowPointer:number|null=null,mousePour=false,held=false,finished=false,paused=false,settleUntil=0;
const stop=()=>{mousePour=false;held=false;cupPointer=null;flowPointer=null;};
const active=()=>!paused&&!finished&&(mousePour||held)&&(ledger.remaining>0||el<HTMLInputElement>('unlimited').checked);
const canvas=view.renderer.domElement;
canvas.addEventListener('pointerdown',e=>{if(cupPointer!==null)return;cupPointer=e.pointerId;canvas.setPointerCapture(e.pointerId);point.copy(view.point(e.clientX,e.clientY));previous.copy(point);mousePour=e.pointerType!=='touch';});
canvas.addEventListener('pointermove',e=>{if(cupPointer===e.pointerId||e.pointerType==='mouse'&&cupPointer===null){point.copy(view.point(e.clientX,e.clientY));}});
const end=(e:PointerEvent)=>{if(e.pointerId===cupPointer){mousePour=false;cupPointer=null;}};
canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('lostpointercapture',end);
canvas.addEventListener('wheel',e=>{e.preventDefault();range.value=String(T.MathUtils.clamp(Number(range.value)-Math.sign(e.deltaY)*.04,.1,1));},{passive:false});
const pour=el('pour');pour.addEventListener('pointerdown',e=>{if(flowPointer!==null)return;e.preventDefault();flowPointer=e.pointerId;pour.setPointerCapture(e.pointerId);held=true;});
for(const event of ['pointerup','pointercancel','lostpointercapture'])pour.addEventListener(event,e=>{if((e as PointerEvent).pointerId===flowPointer){flowPointer=null;held=false;}});
pour.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();held=true;}});pour.addEventListener('keyup',()=>held=false);pour.addEventListener('blur',()=>held=false);
window.addEventListener('blur',()=>{stop();paused=true;});window.addEventListener('focus',()=>{paused=false;previous.copy(point);});document.addEventListener('visibilitychange',()=>{stop();paused=document.hidden;});
el('reset').onclick=()=>{stop();fluid.reset();ledger.refill();finished=false;el('status').textContent='A fresh cup. Take your time.';};
el('refill').onclick=()=>{ledger.refill();el('status').textContent='Pitcher refilled.';};
el('finish').onclick=()=>{stop();finished=true;settleUntil=performance.now()+800;el('status').textContent='Letting your art settle…';setTimeout(()=>{if(finished)el('status').textContent='A cup made by you. Start a fresh cup whenever you like.';},800);};
function tuning(){el('heightLabel').hidden=preset.value!=='Technique';el('tuning').innerHTML=Object.entries(presets[preset.value]).map(([key,value])=>`<label>${key}<input data-param="${key}" type="range" min="${key==='radius'?.01:key==='opacity'?.5:0}" max="${key==='radius'?.08:key==='spread'?.25:key==='opacity'?3:1}" step="0.001" value="${value}"></label>`).join('');el('tuning').querySelectorAll<HTMLInputElement>('input').forEach(input=>input.oninput=()=>{presets[preset.value][input.dataset.param as keyof Preset]=Number(input.value);});}
preset.onchange=()=>{stop();fluid.reset();ledger.refill();finished=false;tuning();};tuning();
el('save').onclick=()=>{try{localStorage.setItem('little-latte-presets',JSON.stringify(presets));el('status').textContent='Preset settings saved on this device.';}catch{el('status').textContent='Storage unavailable. Export your tuning to keep it.';}};
el('restore').onclick=()=>{presets[preset.value]=structuredClone(defaults[preset.value]);tuning();};
el('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(presets,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='latte-presets.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
el<HTMLInputElement>('import').onchange=async e=>{try{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;const data=JSON.parse(await file.text());if(!Object.keys(defaults).every(k=>validPreset(data[k])))throw Error();presets=data;tuning();el('status').textContent='Tuning imported. Save to keep it on this device.';}catch{el('status').textContent='Could not import: expected three valid pouring presets.';}};
el<HTMLInputElement>('left').onchange=e=>el('app').classList.toggle('left',(e.target as HTMLInputElement).checked);
el<HTMLSelectElement>('quality').onchange=e=>{stop();fluid.dispose();fluid=new Fluid(view.renderer,Number((e.target as HTMLSelectElement).value));ledger.refill();finished=false;el('status').textContent='Surface quality changed; fresh cup ready.';};
let audio:AudioContext|undefined,gain:GainNode|undefined;
el<HTMLInputElement>('sound').onchange=async e=>{if((e.target as HTMLInputElement).checked){try{if(!audio){audio=new AudioContext();const buffer=audio.createBuffer(1,audio.sampleRate*2,audio.sampleRate);const samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=Math.random()*2-1;const source=audio.createBufferSource();source.buffer=buffer;source.loop=true;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=750;gain=audio.createGain();gain.gain.value=0;source.connect(filter).connect(gain).connect(audio.destination);source.start();}await audio.resume();}catch{el('status').textContent='Pour sound unavailable in this browser.';}}else if(gain)gain.gain.value=0;};
let last=performance.now(),accumulator=0,frames=0,report=last;
function frame(now:number){const elapsed=Math.min((now-last)/1000,.1);last=now;const pouring=active();const flow=Number(range.value);const high=preset.value==='Technique'&&el<HTMLSelectElement>('height').value==='high';
 if(!paused&&(!finished||now<settleUntil)){accumulator+=elapsed;const steps=Math.floor(accumulator*60);const origin=previous.clone();for(let i=0;i<steps;i++){const a=origin.clone().lerp(point,i/steps).multiplyScalar(.5).addScalar(.5),b=origin.clone().lerp(point,(i+1)/steps).multiplyScalar(.5).addScalar(.5);let used=0;if(pouring)used=el<HTMLInputElement>('unlimited').checked?flow/60:ledger.spend(flow,1/60);fluid.step(a,b,used*60,1/60,presets[preset.value],high);accumulator-=1/60;}if(steps)previous.copy(point);}
 if(gain&&audio)gain.gain.setTargetAtTime(pouring&&el<HTMLInputElement>('sound').checked?flow*.06:0,audio.currentTime,.03);
 view.coffeeMaterial.uniforms.field.value=fluid.texture;view.render(point,pouring,flow,high);el<HTMLProgressElement>('budget').value=ledger.remaining;el('milk').textContent=el<HTMLInputElement>('unlimited').checked?'∞':`${Math.ceil(ledger.remaining)}%`;
 if(ledger.remaining===0&&!finished&&!el<HTMLInputElement>('unlimited').checked){stop();el('status').textContent='Pitcher empty. Refill or enjoy your finished cup.';}
 frames++;if(now-report>1000){el('performance').textContent=`${Math.round(frames*1000/(now-report))} fps · ${fluid.size}² surface · 60 Hz simulation`;frames=0;report=now;}requestAnimationFrame(frame);}
requestAnimationFrame(frame);

