import type {createScene} from './scene';
import {roomCatalog,type RoomConfig,type DecorationKind} from './room-config';
import {decorationLabels} from './workshop-props';
export function mountWorldPieces(view:ReturnType<typeof createScene>,hooks:{active:()=>boolean;room:()=>RoomConfig;apply:(room:RoomConfig)=>void}){
 const main=document.querySelector('main')!,canvas=view.renderer.domElement;
 const labels=document.createElement('nav');labels.className='world-piece-labels';labels.setAttribute('aria-label','Counter objects');main.append(labels);
 const panel=document.createElement('section');panel.className='world-piece-panel';panel.hidden=true;panel.setAttribute('aria-label','Object actions');main.append(panel);
 let selection:{kind:string;id?:string}|undefined,last=0,hoveredDecoration:string|undefined,down:{x:number;y:number;kind:string}|undefined;
 function close(){panel.hidden=true;selection=undefined;}
 function action(text:string,run:()=>void){const b=document.createElement('button');b.textContent=text;b.onclick=run;panel.append(b);}
 function choice(key:keyof typeof roomCatalog,parent:HTMLElement=panel){const label=document.createElement('label');label.textContent=({mugSize:'Size',cup:'Glaze',jugShape:'Jug',pitcher:'Finish',light:'Light',fixture:'Fixture',machine:'Machine',kettle:'Kettle'} as Record<string,string>)[key]||key;const select=document.createElement('select');for(const [value,item] of Object.entries(roomCatalog[key])){const o=document.createElement('option');o.value=value;o.textContent=item.label;select.append(o);}select.value=String(hooks.room()[key]);select.onchange=()=>{const next=structuredClone(hooks.room());(next as unknown as Record<string,string>)[key]=select.value;hooks.apply(next);};label.append(select);parent.append(label);}
 function open(kind:string,id?:string){if(!hooks.active())return;selection={kind,id};panel.replaceChildren();panel.hidden=false;const header=document.createElement('div');header.className='piece-heading';const title=document.createElement('strong');title.textContent=kind==='cup'?'Your cup':kind==='milk'?'Milk jug':kind==='tools'?'Barista tools':kind==='light'?'Lighting':kind==='espresso'?'Espresso machine':kind==='pour-over'?'Pour-over kettle':'Counter object';const dismiss=document.createElement('button');dismiss.textContent='×';dismiss.setAttribute('aria-label','Close object actions');dismiss.onclick=close;header.append(title,dismiss);panel.append(header);
  if(kind==='cup'){action('Pour this cup',()=>{close();document.getElementById('cupView')!.click();});const appearance=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Cup style';appearance.append(summary);panel.append(appearance);choice('mugSize',appearance);choice('cup',appearance);action('Next cup',()=>{document.getElementById('nextCup')!.click();close();});}
  else if(kind==='milk'){const label=document.createElement('label');label.textContent='Milk';const original=document.querySelector<HTMLSelectElement>('#milkTexture')!,select=original.cloneNode(true) as HTMLSelectElement;select.removeAttribute('id');select.value=original.value;select.onchange=()=>{original.value=select.value;original.dispatchEvent(new Event('change'));};label.append(select);panel.append(label);const appearance=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Jug style';appearance.append(summary);panel.append(appearance);choice('jugShape',appearance);choice('pitcher',appearance);const tip=document.createElement('small');tip.textContent='Silky milk: stop at 5–9 s. Pour low to draw; lift to cut.';panel.append(tip);action('Go steam milk',()=>{close();document.getElementById('refill')!.click();});}
  else if(kind==='light'){choice('light');choice('fixture');}
  else if(kind==='espresso'||kind==='pour-over'){choice(kind==='espresso'?'machine':'kettle');action('Use this station',()=>{close();const label=kind==='espresso'?'Go to machine':'Go to kettle';Array.from(document.querySelectorAll<HTMLButtonElement>('.corner-more-menu button')).find(b=>b.textContent===label)?.click();});}
  else if(kind==='tools'){for(const [value,text] of [['pick','Foam pick'],['spoon','Foam spoon'],['pour','Milk pour']])action(text,()=>{close();document.getElementById('cupView')!.click();const select=document.querySelector<HTMLSelectElement>('#surfaceTool')!;select.value=value;select.dispatchEvent(new Event('change'));});}
  else {const decoration=hooks.room().decorations.find(d=>d.id===id);if(!decoration){close();return;}title.textContent=decorationLabels[decoration.kind];const select=document.createElement('select');select.setAttribute('aria-label','Swap decoration');for(const [value,label] of Object.entries(decorationLabels)){const option=document.createElement('option');option.value=value;option.textContent=label;select.append(option);}select.value=decoration.kind;select.onchange=()=>{const next=structuredClone(hooks.room());next.decorations.find(d=>d.id===id)!.kind=select.value as DecorationKind;hooks.apply(next);};panel.append(select);action('Turn ↻',()=>{const next=structuredClone(hooks.room());const d=next.decorations.find(d=>d.id===id)!;d.rotation=Math.atan2(Math.sin(d.rotation+Math.PI/4),Math.cos(d.rotation+Math.PI/4));hooks.apply(next);});action('Remove',()=>{const next=structuredClone(hooks.room());next.decorations=next.decorations.filter(d=>d.id!==id);hooks.apply(next);close();});const hint=document.createElement('small');hint.textContent='Drag the object on the counter to move it.';panel.append(hint);}
 }
 const buttons=new Map<string,HTMLButtonElement>();for(const [kind,text] of [['cup','Cup'],['milk','Milk jug'],['tools','Tools'],['light','Lighting'],['decoration','Object']]){const b=document.createElement('button');b.textContent=text;b.dataset.piece=kind;b.onclick=()=>open(kind,kind==='decoration'?hoveredDecoration:undefined);labels.append(b);buttons.set(kind,b);}
 canvas.addEventListener('counter-interact',event=>{const detail=(event as CustomEvent).detail;open(detail.kind,detail.id);});
 canvas.addEventListener('pointerdown',e=>{if(!hooks.active()||e.button!==0)return;const kind=view.hitWorldPiece(e.clientX,e.clientY);if(kind)down={x:e.clientX,y:e.clientY,kind};else close();});
 canvas.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<6)open(down.kind);down=undefined;});canvas.addEventListener('pointercancel',()=>{down=undefined;});canvas.addEventListener('pointermove',e=>{if(!hooks.active()||e.buttons)return;hoveredDecoration=view.pickDecoration(e.clientX,e.clientY)?.id;});
 canvas.addEventListener('contextmenu',e=>{if(!hooks.active())return;const kind=view.hitStation(e.clientX,e.clientY);if(kind==='espresso'||kind==='pour-over'){e.preventDefault();open(kind);}});
 document.getElementById('cupView')!.addEventListener('click',close);
 function frame(now:number){requestAnimationFrame(frame);if(document.hidden||now-last<150)return;last=now;const active=hooks.active()&&!main.classList.contains('station-working');labels.hidden=!active;if(!active){close();return;}for(const [kind,b] of buttons){const point=kind==='decoration'&&!hoveredDecoration?null:view.worldPieceScreen(kind,hoveredDecoration);b.hidden=!point;if(kind==='decoration'&&hoveredDecoration){const d=hooks.room().decorations.find(d=>d.id===hoveredDecoration);const text=d?decorationLabels[d.kind]:'Object';if(b.textContent!==text)b.textContent=text;}if(point){b.style.left=point.x+'px';b.style.top=point.y+'px';}}if(selection){const point=selection.kind==='espresso'||selection.kind==='pour-over'?view.stationScreen(selection.kind):view.worldPieceScreen(selection.kind,selection.id);if(point){panel.style.left=Math.max(8,Math.min(main.clientWidth-panel.offsetWidth-8,point.x-120))+'px';panel.style.top=Math.max(58,Math.min(main.clientHeight-panel.offsetHeight-8,point.y+20))+'px';}}}
 requestAnimationFrame(frame);
}
